# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tamplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1020, 678)
        Form.setMinimumSize(QtCore.QSize(1020, 678))
        Form.setMaximumSize(QtCore.QSize(1020, 678))
        Form.setStyleSheet("#Form{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(75, 121, 161, 255), stop:1 rgba(40, 62, 81, 255));}\n"
"*{font-family:  century gothic;}")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(50, 40, 921, 591))
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setStyleSheet("#widget{\n"
"background: rgba(51, 51, 51, 0.8);\n"
"border-radius: 15px;\n"
"}")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(200, 520, 543, 33))
        self.pushButton.setStyleSheet("\n"
"#pushButton{\n"
"font-family:  century gothic;\n"
"border-radius: 15px;\n"
"\n"
"background-color: #fff;\n"
"font-size: 20pt;}\n"
"\n"
"\n"
"#pushButton:hover{\n"
"transition: transform 1s;\n"
"\n"
"\n"
"border: 5px, 5px, 5px, 5px solid #717072;\n"
"background: #eee;\n"
"font-size: 20pt;}\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(220, -30, 543, 161))
        self.label.setStyleSheet("font-family:  century gothic;\n"
"font-size: 40pt;\n"
"color: white;")
        self.label.setObjectName("label")
        self.right_btn = QtWidgets.QPushButton(self.widget)
        self.right_btn.setGeometry(QtCore.QRect(840, 280, 75, 51))
        self.right_btn.setStyleSheet("#right_btn{\n"
"\n"
"background: transparent;\n"
"}\n"
"\n"
"#right_btn:hover{\n"
"margin-left: 10px;\n"
"\n"
"}\n"
"")
        self.right_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/right-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_btn.setIcon(icon)
        self.right_btn.setIconSize(QtCore.QSize(50, 50))
        self.right_btn.setObjectName("right_btn")
        self.left_btn = QtWidgets.QPushButton(self.widget)
        self.left_btn.setGeometry(QtCore.QRect(10, 290, 75, 51))
        self.left_btn.setStyleSheet("#left_btn{\n"
"\n"
"background: transparent;\n"
"}\n"
"\n"
"#left_btn:hover{\n"
"margin-right: 10px;\n"
"\n"
"}\n"
"")
        self.left_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/imgonline-com-ua-Mirror-av0m9Ew8M3znRrp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_btn.setIcon(icon1)
        self.left_btn.setIconSize(QtCore.QSize(50, 50))
        self.left_btn.setObjectName("left_btn")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(50, 210, 839, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.slide_preview = QtWidgets.QLabel(self.frame)
        self.slide_preview.setGeometry(QtCore.QRect(60, 50, 211, 111))
        self.slide_preview.setAutoFillBackground(True)
        self.slide_preview.setText("")
        self.slide_preview.setPixmap(QtGui.QPixmap("3x/slide_preview.png"))
        self.slide_preview.setScaledContents(True)
        self.slide_preview.setObjectName("slide_preview")
        self.p1 = QtWidgets.QLabel(self.frame)
        self.p1.setGeometry(QtCore.QRect(300, 30, 241, 141))
        self.p1.setAutoFillBackground(True)
        self.p1.setText("")
        self.p1.setPixmap(QtGui.QPixmap("3x/p1.png"))
        self.p1.setScaledContents(True)
        self.p1.setObjectName("p1")
        self.p3 = QtWidgets.QLabel(self.frame)
        self.p3.setGeometry(QtCore.QRect(568, 50, 211, 111))
        self.p3.setAutoFillBackground(True)
        self.p3.setText("")
        self.p3.setPixmap(QtGui.QPixmap("3x/p3.png"))
        self.p3.setScaledContents(True)
        self.p3.setObjectName("p3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Далее"))
        self.label.setText(_translate("Form", "Выберите шаблон"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
